const projectData = [
    {
        id: 1,
        title: 'All Fresh Laundry',
        description: 'A full-featured online store with payment integration',
        image: '/Images/AllFreshLaundry.png',
        category: 'web',
        technologies: ['Laravel', 'PHP', 'Javascript', 'MySQL'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 2,
        title: 'Library Management',
        description: 'A productivity app to manage tasks and projects',
        image: '/Images/LibManage.png',
        category: 'web',
        technologies: ['Springboot', 'Java', 'H2'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 3,
        title: 'Prime',
        description: 'A responsive portfolio website for creatives',
        image: '/Images/Prime.png',
        category: 'web',
        technologies: ['Next.js', 'React.js', 'Typescript', 'Javascript', 'Tailwind CSS' ],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 4,
        title: 'Staff Management',
        description: 'A responsive portfolio website for creatives',
        image: '/Images/AllFreshLaundry.png',
        category: 'web',
        technologies: ['Laravel', 'PHP', 'PostgreSQL' ,'Tailwind CSS'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 5,
        title: 'Portofolio',
        description: 'A responsive portfolio website for creatives',
        image: '/Images/AllFreshLaundry.png',
        category: 'web',
        technologies: ['React.js', 'Tailwind CSS'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 6,
        title: 'Chatbot',
        description: 'Real-time weather data visualization',
        image: '/Images/AllFreshLaundry.png',
        category: 'ml',
        technologies: ['Python', 'Pytorch'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 7,
        title: 'Regression',
        description: 'Real-time weather data visualization',
        image: '/Images/AllFreshLaundry.png',
        category: 'ml',
        technologies: ['Python', 'Weather API', 'Chart.js'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 8,
        title: 'Data Analysis and Visualization Dashboard',
        description: 'Real-time weather data visualization',
        image: '/Images/AllFreshLaundry.png',
        category: 'ml',
        technologies: ['Python', 'Streamlit', 'Chart.js'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 9,
        title: 'Consumer Complaint Cluster and Classification',
        description: 'Real-time weather data visualization',
        image: '/Images/AllFreshLaundry.png',
        category: 'ml',
        technologies: ['Python', 'K-Means', 'Random Forest'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 10,
        title: 'Aksara Sunda Detection',
        description: 'Real-time weather data visualization',
        image: '/Images/AllFreshLaundry.png',
        category: 'ml',
        technologies: ['Python', 'Yolov5'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 11,
        title: 'Library App',
        description: 'Real-time weather data visualization',
        image: '/Images/apk-perpus.png',
        category: 'mobile',
        technologies: ['Java', 'MySQL'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 12,
        title: 'Workmates',
        description: 'Real-time weather data visualization',
        image: '/Images/AllFreshLaundry.png',
        category: 'mobile',
        technologies: ['Flutter'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 13,
        title: 'Pillars of Islam Learning App(AR)',
        description: 'Real-time weather data visualization',
        image: '/Images/Grafkom.png',
        category: 'mobile',
        technologies: ['Unity', 'Weather API'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 14,
        title: 'BSO Android Logo',
        description: 'Real-time weather data visualization',
        image: '/Images/BSO.png',
        category: 'design',
        technologies: ['Canva'],
        liveLink: '#',
        codeLink: '#',
    },
    {
        id: 15,
        title: 'Bloodmoon',
        description: 'Real-time weather data visualization',
        image: '/Images/Bloodmoon.png',
        category: 'design',
        technologies: ['unity'],
        liveLink: '#',
        codeLink: '#',
    },
];
export default projectData;